sonar.organization=dariiatar
sonar.projectKey=dariiatar_refactoring_project2
sonar.projectName=SportBook UA
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.language=py
sonar.python.version=3.11

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml

sonar.exclusions=**/migrations/**,**/seed/**,**/__pycache__/**,**/uploads/**,**/frontend/**,**/.venv/**,**/htmlcov/**,**/*.pyc

sonar.coverage.exclusions=**/config/**,**/main.py,**/dto/**
